/*
 * XenForo admin.min.js
 * Copyright 2010-2017 XenForo Ltd.
 * Released under the XenForo License Agreement: https://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,d,c){b instanceof String&&(b=String(b));for(var e=b.length,a=0;a<e;a++){var f=b[a];if(d.call(c,f,a,b))return{i:a,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,c){b!=Array.prototype&&b!=Object.prototype&&(b[d]=c.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,d,c,e){if(d){c=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var a=b[e];a in c||(c[a]={});c=c[a]}b=b[b.length-1];e=c[b];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
!function(b,d,c,e){XF.OffCanvasBuilder.acpNav=function(a,b){a.on("off-canvas:opening",function(){a.css("position","")})};XF.AdminNav=XF.Element.newHandler({options:{topOffset:".p-header",stickyTarget:"| .js-navSticky",sectionTogglers:".js-navSectionToggle",toggleTarget:".p-nav-section",toggleSubTarget:".p-nav-listSection",navTester:"| .js-navTester"},$stickyTarget:null,init:function(){this.$stickyTarget=XF.findRelativeIf(this.options.stickyTarget,this.$target);this.refreshSticky();this.$target.on("click",
this.options.sectionTogglers,b.proxy(this,"togglerClick"));b(d).resize(b.proxy(this,"refreshSticky"))},isOffCanvas:function(){var a=XF.findRelativeIf(this.options.navTester,this.$target);return a.length?"off-canvas"==d.getComputedStyle(a[0]).getPropertyValue("font-family").replace(/"/g,""):!1},refreshSticky:function(){var a=this.$stickyTarget,b=a.data("sticky_kit");this.isOffCanvas()?b&&a.trigger("sticky_kit:detach").removeData("sticky_kit"):b||(this.$target.trigger("off-canvas:close",{instant:!0}),
b=XF.findRelativeIf(this.options.topOffset,this.$target).height(),a.stick_in_parent({offset_top:b}))},togglerClick:function(a){a.preventDefault();a=b(a.target).closest(this.options.toggleTarget);var c=this.options.toggleSubTarget;a.siblings().not(a).each(function(){var a=b(this);a.removeClassTransitioned("is-active");a.find(c).removeClassTransitioned("is-active")});a.toggleClassTransitioned("is-active",function(){XF.layoutChange()});a.find(c).toggleClassTransitioned("is-active")}});XF.AdminSearch=
XF.Element.newHandler({options:{input:"| .js-adminSearchInput",results:"| .js-adminSearchResults",resultsWrapper:"| .js-adminSearchResultsWrapper",toggleClass:"is-active"},$input:null,$results:null,$resultsWrapper:null,xhr:null,init:function(){var a=this.$target;var c=this.$input=XF.findRelativeIf(this.options.input,a);this.$results=XF.findRelativeIf(this.options.results,a);this.$resultsWrapper=XF.findRelativeIf(this.options.resultsWrapper,a);a.submit(b.proxy(this,"submit"));XF.watchInputChangeDelayed(c,
function(){a.submit()})},submit:function(a){a.preventDefault();a=this.$target;var c=this.$results,d=this,e=this.$resultsWrapper,g=this.options.toggleClass;b.trim(this.$input.val()).length?(this.xhr&&this.xhr.abort(),this.xhr=XF.ajax("post",a.attr("action"),a.serializeArray(),function(a){a.html&&XF.setupHtmlInsert(a.html,function(a,b,f){a.length?(c.html(a),f(),e.addClass(g),c.addClassTransitioned(g)):d.emptyResults()})})):this.emptyResults()},emptyResults:function(){var a=this.$results,b=this.$resultsWrapper,
c=this.options.toggleClass;a.removeClassTransitioned(c,function(){a.empty();b.removeClass(c)})}});XF.Element.register("admin-nav","XF.AdminNav");XF.Element.register("admin-search","XF.AdminSearch")}(jQuery,window,document);
