/*
 * XenForo embed.min.js
 * Copyright 2010-2017 XenForo Ltd.
 * Released under the XenForo License Agreement: https://xenforo.com/license-agreement
 */
!function(b,h,g,k){XF.OembedFetcher=XF.Element.newHandler({options:{provider:"",id:""},init:function(){this.options.provider&&this.options.id&&b.ajax(XF.canonicalizeUrl("oembed.php"),{data:{provider:this.options.provider,id:this.options.id.replace(/#/,"{{_hash_}}")},success:b.proxy(this,"handleResponse")})},handleResponse:function(a,b,c){a.hasOwnProperty("html")?this.insertOembedHtml(a,c.getResponseHeader("X-Oembed-Retain-Scripts")?!0:!1):"photo"==a.type?this.insertOembedImage(a):a.hasOwnProperty("xf-oembed-error")&&
this.oembedFetchError(a)},insertOembedHtml:function(a,d){if(void 0===a.html)return!1;XF.setupHtmlInsert({content:a.html},b.proxy(function(a,b,d){this.$target.addClass("bbOembed--loaded").html(a);this.onComplete()},this),d)},insertOembedImage:function(a){var d=b("<a />",this.getImageLinkData(a));b('<img class="bbImage" data-zoom-target="1" />').appendTo(d).on("load",b.proxy(this,"onComplete")).attr("src",a.url);this.$target.empty().append(d)},oembedFetchError:function(a){this.$target.addClass("bbOembed--failure");
console.warn("Unable to fetch %s media id: %s",this.options.provider,this.options.id)},getImageLinkData:function(a){var b={rel:"external",target:"_blank"},c={href:["web_page","web_page_short_url","author_url"],title:["title"],"data-author":["author_name"]},e="",f;for(e in c)for(f=0;f<c[e].length;f++)if(a.hasOwnProperty(c[e][f])){b[e]=a[c[e][f]];break}return b},onComplete:function(){b(g).trigger("embed:loaded");XF.layoutChange()}});XF.TweetRenderer=XF.Element.newHandler({options:{tweetId:null,lang:"en",
dnt:"false",related:null,via:null,conversation:"all",cards:"visible",align:null,theme:"light",linkColor:"#2b7bb9"},init:function(){h.twttr&&!isNaN(this.options.tweetId)&&twttr.ready(b.proxy(function(a){a.widgets.createTweet(this.options.tweetId,this.$target.get(0),this.options).then(function(){b(g).trigger("embed:loaded");XF.layoutChange()})},this))}});XF.Element.register("oembed","XF.OembedFetcher");XF.Element.register("tweet","XF.TweetRenderer")}(jQuery,window,document);
