/*
 * XenForo inline_mod.min.js
 * Copyright 2010-2017 XenForo Ltd.
 * Released under the XenForo License Agreement: https://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,h,g){b instanceof String&&(b=String(b));for(var k=b.length,a=0;a<k;a++){var c=b[a];if(h.call(g,c,a,b))return{i:a,v:c}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,h,g){b!=Array.prototype&&b!=Object.prototype&&(b[h]=g.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,h,g,k){if(h){g=$jscomp.global;b=b.split(".");for(k=0;k<b.length-1;k++){var a=b[k];a in g||(g[a]={});g=g[a]}b=b[b.length-1];k=g[b];h=h(k);h!=k&&null!=h&&$jscomp.defineProperty(g,b,{configurable:!0,writable:!0,value:h})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,g){return $jscomp.findInternal(this,b,g).v}},"es6","es3");
!function(b,h,g,k){XF.InlineMod=XF.Element.newHandler({options:{type:null,href:null,cookieBase:"inlinemod",toggle:"input[type=checkbox].js-inlineModToggle",toggleContainer:".js-inlineModContainer",containerClass:"is-mod-selected",actionTrigger:".js-inlineModTrigger",counter:".js-inlineModCounter",viewport:"body"},cookie:null,$action:null,xhr:null,init:function(){if(this.options.type){this.options.href||console.error("No inline mod href specified");this.cookie=this.options.cookieBase+"_"+this.options.type;
this.$target.on("click",this.options.toggle,b.proxy(this,"onToggle"));this.$target.on("click",this.options.actionTrigger,b.proxy(this,"onActionTrigger"));var a=this.getCookieValue();this._initialLoad(a);this._updateCounter(a.length)}else console.error("No inline mod type specified")},_initialLoad:function(a){this.$target.find(this.options.toggle).each(function(){b(this).prop("checked",!1)});var c={};if(a.length){this.$target.find(this.options.toggle).each(function(){var a=b(this);c[a.val()]=a});for(var d=
a.length,e,f=0;f<d;f++)e=a[f],c[e]&&(c[e].prop("checked",!0),this.toggleContainer(c[e],!0))}},recalculateFromCookie:function(){for(var a=this.getCookieValue(),c=a.length,d={},e=this,f=0;f<c;f++)d[a[f]]=!0;this.$target.find(this.options.toggle).each(function(){var a=b(this),c=a.is(":checked"),f=d[a.val()]?!0:!1;c&&!f?(a.prop("checked",!1),e.toggleContainer(a,!1)):!c&&f&&(a.prop("checked",!0),e.toggleContainer(a,!0))})},deselect:function(){this.setCookieValue([]);this.recalculateFromCookie();this.hideBar()},
selectAll:function(){var a=this.getCookieValue();this.$target.find(this.options.toggle).each(function(){var c=parseInt(b(this).val(),10);-1===b.inArray(c,a)&&a.push(c)});this.setCookieValue(a);this.recalculateFromCookie();return a},deselectPage:function(){var a=this.getCookieValue(),c=[],d=[];this.$target.find(this.options.toggle).each(function(){d.push(parseInt(b(this).val(),10))});for(var e=0;e<a.length;e++)-1===b.inArray(a[e],d)&&c.push(a[e]);this.setCookieValue(c);this.recalculateFromCookie();
c.length?this.loadBar():this.hideBar();return c},onToggle:function(a){a=b(a.target);var c=a.is(":checked");var d=this.toggleSelectedInCookie(a.val(),c);this.toggleContainer(a,c);d.length?this.loadBar():this.hideBar()},onActionTrigger:function(a){a.preventDefault();this.loadBar()},loadBar:function(a){var c=this;this.xhr&&this.xhr.abort();this.xhr=XF.ajax("GET",this.options.href,{type:this.options.type},function(b){c._showBar(b,a)})},_showBar:function(a,c){this.xhr=null;if(a.html){var d=this;XF.setupHtmlInsert(a.html,
function(a,f,g){f=!1;d.$bar&&(f=!0,d.$bar.remove(),d.$bar=null);d._setupBar(a);d.$bar=a;XF.bottomFix(a);if(XF.browser.ios){var e=b('<div class="inlineModBarCover" />'),h=d.$bar,k=h.find(".js-inlineModAction");e.click(function(){k.blur()});k.on({focus:function(){h.before(e)},blur:function(){setTimeout(function(){e.remove()},200)}})}f&&a.css("transition-duration","0s");a.addClassTransitioned("is-active");f&&setTimeout(function(){a.css("transition-duration","")},0);c&&c(a)})}},_setupBar:function(a){a.on("click",
":submit",b.proxy(this,"submit")).on("click",".js-inlineModClose",b.proxy(this,"hideBar")).on("click",".js-inlineModSelectAll",b.proxy(this,"onSelectAllClick"));var c=this.$target.find(this.options.toggle);c.length==c.filter(":checked").length&&a.find("input[type=checkbox].js-inlineModSelectAll").prop("checked",!0)},onSelectAllClick:function(a){b(a.target).is(":checked")?this.selectAll().length?this.loadBar(function(a){a.find("input[type=checkbox].js-inlineModSelectAll").prop("checked",!0)}):this.deselect():
this.deselectPage()},submit:function(){if(this.$bar){var a=this.$bar.find(".js-inlineModAction");if(a.length){if(a=a.val())if("deselect"==a)this.deselect();else{var c=this;XF.ajax("POST",this.options.href,{type:this.options.type,action:a},function(a){c._handleSubmitResponse(a)},{skipDefaultSuccess:!0})}}else console.error("No action selector found.")}},_handleSubmitResponse:function(a){a.html?XF.setupHtmlInsert(a.html,function(a,b){a=XF.getOverlayHtml({html:a,title:b.h1||b.title});XF.showOverlay(a)}):
"ok"==a.status&&a.redirect?a.message?XF.flashMessage(a.message,1E3,function(){XF.redirect(a.redirect)}):XF.redirect(a.redirect):XF.alert("Unexpected response");this.hideBar()},hideBar:function(){if(this.$bar){var a=this;this.$bar.removeClassTransitioned("is-active",function(){a.$bar&&a.$bar.remove();a.$bar=null})}},_updateCounter:function(a){var b=this.$target.find(this.options.actionTrigger),d=b.find(".inlineModButton");d.length||(d=b);d.toggleClass("is-mod-active",0<a);this.$target.find(this.options.counter).text(a)},
toggleContainer:function(a,b){b=b?"addClass":"removeClass";a.closest(this.options.toggleContainer)[b](this.options.containerClass)},toggleSelectedInCookie:function(a,c){a=parseInt(a,10);var d=this.getCookieValue(),e=b.inArray(a,d),f=!1;c?0>e&&(d.push(a),f=!0):0<=e&&(d.splice(e,1),f=!0);return f?this.setCookieValue(d):d},getCookieValue:function(){var a=XF.Cookie.get(this.cookie);if(!a)return[];a=a.split(",");for(var b=a.length,d=0;d<b;d++)a[d]=parseInt(a[d],10);return a},setCookieValue:function(a){a.length?
(a.sort(function(a,b){return a-b}),XF.Cookie.set(this.cookie,a.join(","))):XF.Cookie.remove(this.cookie);this._updateCounter(a.length);return a}});XF.Element.register("inline-mod","XF.InlineMod")}(jQuery,window,document);
